# Generated by Django 5.1.5 on 2025-01-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='UserSystem',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='formapp.base')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('surname', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuários',
            },
            bases=('formapp.base',),
        ),
    ]
