# Generated by Django 5.1.5 on 2025-01-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersystem',
            name='password',
            field=models.CharField(editable=False, max_length=255, verbose_name='Senha'),
        ),
    ]
